apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# namespace: production
# commonLabels:
#   env: prod
#   tier: api

bases:
  - ../../base

resources:
  - namespace.yaml

images:
  - name: ghcr.io/mintak21/qiitanwrapper/api
    newTag: 0179e7d9cf5f7ef106d654fcd73df3f78a4f1040

configMapGenerator:
  - name: qiitanwrapper-api
    literals:
      - DUMMY_ENV=production
