apiVersion: apps/v1
kind: Deployment
metadata:
  name: qiitawrapper
  labels:
    app: qiitawrapper
spec:
  selector:
    matchLabels:
      app: qiitawrapper
      tier: api
  template:
    metadata:
      labels:
        app: qiitawrapper
        tier: api
    spec:
      containers:
        - name: qiitawrapper-api
          image: ghcr.io/mintak21/qiitanwrapper/api
          ports:
            - containerPort: 8090
