name: Build Docker Image

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to ECR
        id: login-ecr
        uses: elgohr/ecr-login-action@master
        with:
          access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: ap-northeast-1

      - name: Kaniko build
        id: kaniko
        uses: aevea/action-kaniko@master
        env:
          IMAGE_TAG: ${{ github.ref }}-${{ github.sha }}
        with:
          image: mintak/qiitawrapper/api
          path: .
          build_file: deployment/dockerfile/api/Dockerfile
          tag: $IMAGE_TAG
          username: ${{ steps.login-ecr.outputs.username }}
          password: ${{ steps.login-ecr.outputs.password }}
          registry: ${{ steps.login-ecr.outputs.registry }}
          cache: true
          cache_registry: mintak/cache/qiitawrapper/api
