name: Unit Test and Check Docker Image

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  unit-test:
    name: Unit Test
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout code
        id: checkout
        uses: actions/checkout@v2

      - name: Set up Golang
        id: setup
        uses: actions/setup-go@v1
        with:
          go-version: 1.14

      - name: Execute Unit Test
        id: test
        run: echo dummy test done

  scan-vulnerability:
    name: Scan Vulnerability By Trivy
    runs-on: ubuntu-18.04
    needs: build-image
    steps:
      - name: Setup Go
        id: setup
        uses: actions/setup-go@v1
        with:
          go-version: 1.14

      - name: Checkout code
        id: checkout
        uses: actions/checkout@v2

      - name: Build image from Dockerfile
        id: build
        env:
          DOCKER_FILE: deployment/dockerfile/api/Dockerfile
          TAG: mintak/qiitaapi/api:check-image
        run: |
          docker build -f ${DOCKER_FILE} -t ${TAG} .
          echo "::set-output name=tag::${TAG}"

      - name: Run Vulnerability Scanner
        id: vul-scan
        uses: aquasecurity/trivy-action@0.0.8
        with:
          image-ref: ${{ steps.build.outputs.tag }}
          format: table
          exit-code: 1
          ignore-unfixed: true
          severity: "CRITICAL,HIGH"

      # ベータ版のようだが、TrivyとDockleの2つを使ってチェックしてくれるAction
      - name: Run Vulnerability/Security Scanner
        id: run-vul-sec-scanner
        uses: Azure/container-scan@v0
        with:
          image-name: mintak/qiitaapi/api:check-image
          severity-threshold: HIGH
          run-quality-checks: true
